In [5]:
this_pix = 7
this_list = 4

In [6]:
import pandas as pd
import numpy as np
from os import walk
from os.path import join
from all_p import ClusterFile, pix2dict, pic_all_filters, make_mask

In [7]:
mtx_dir = '/home/rt2122/data/train/mtx'
mtx_files = next(walk(mtx_dir))[-1]
data_dir = '/home/rt2122/data/train/clear/'
data_files = next(walk(data_dir))[-1]

In [8]:
mtx_files = list(filter(lambda name:ClusterFile(name).params['id_list'] == this_list, mtx_files))
mtx_files = sorted(mtx_files, key=lambda name:ClusterFile(name).params['id_patch'])
data_files = list(filter(lambda name:ClusterFile(name).params['id_list'] == this_list, data_files))
data_files = sorted(data_files, key=lambda name:ClusterFile(name).params['id_patch'])

In [9]:
planck = pd.read_csv('../src_data/planck_z.csv', index_col='index')
planck_pix = planck[planck['pix']==this_pix]
planck_pix.shape

(42, 10)

In [13]:
dist=0.8454
filters_dir = '/home/rt2122/data/train/filters/'

In [14]:
for data, mtx in zip(data_files, mtx_files):
    print(data, mtx)
    #continue
    
    patch = pd.read_csv(join(data_dir, data), index_col='Unnamed: 0')
    patch.index.name = 'index'
    pic_matr = np.load(join(mtx_dir, mtx))
    
    dict_mtx = pix2dict(pic_matr)
    del pic_matr
    
    all_f = pic_all_filters(patch, dict_mtx, base=-4, size=2048)
    cf = ClusterFile(data)
    ra = cf.params['ra']
    dec = cf.params['dec']
    cf.params['typ'] = 'd'
    cf.params['state']='grizy'
    np.save(join(filters_dir, cf.file()), all_f)
    del all_f
    
    mask = make_mask(ra, dec, dict_mtx, planck_pix, patch_radius=dist, size=2048)
    mask *= 255
    cf.params['typ'] = 'm'
    cf.params['state'] = 'm'
    
    np.save(join(filters_dir, cf.file()), mask)

tdat_il4_ip0_ra163.1320_dec58.3101_scl_in7.csv tmtx_il4_ip0_ra163.1320_dec58.3101_in7.npy



mask 0
tdat_il4_ip1_ra187.3484_dec47.1498_scl_in7.csv tmtx_il4_ip1_ra187.3484_dec47.1498_in7.npy



mask 1
tdat_il4_ip2_ra174.6845_dec66.8075_scl_in7.csv tmtx_il4_ip2_ra174.6845_dec66.8075_in7.npy



mask 0
tdat_il4_ip3_ra177.7263_dec63.0286_scl_in7.csv tmtx_il4_ip3_ra177.7263_dec63.0286_in7.npy



mask 0
tdat_il4_ip4_ra193.2090_dec49.3313_scl_in7.csv tmtx_il4_ip4_ra193.2090_dec49.3313_in7.npy



mask 0
tdat_il4_ip5_ra180.5136_dec58.6707_scl_in7.csv tmtx_il4_ip5_ra180.5136_dec58.6707_in7.npy



mask 1
tdat_il4_ip6_ra184.1741_dec51.0555_scl_in7.csv tmtx_il4_ip6_ra184.1741_dec51.0555_in7.npy



mask 1
tdat_il4_ip7_ra168.5814_dec58.6462_scl_in7.csv tmtx_il4_ip7_ra168.5814_dec58.6462_in7.npy



mask 0
tdat_il4_ip8_ra201.8420_dec49.1519_scl_in7.csv tmtx_il4_ip8_ra201.8420_dec49.1519_in7.npy



mask 0
tdat_il4_ip9_ra195.1921_dec60.5488_scl_in7.csv tmtx_il4_ip9_ra195.1921_dec60.5488_in7.npy



mask 1
tdat_il4_ip10_ra176.3175_dec51.7430_scl_in7.csv tmtx_il4_ip10_ra176.3175_dec51.7430_in7.npy



mask 0
tdat_il4_ip11_ra198.7069_dec39.2329_scl_in7.csv tmtx_il4_ip11_ra198.7069_dec39.2329_in7.npy



mask 0
tdat_il4_ip12_ra177.1410_dec51.9537_scl_in7.csv tmtx_il4_ip12_ra177.1410_dec51.9537_in7.npy



mask 1
tdat_il4_ip13_ra191.6882_dec49.8275_scl_in7.csv tmtx_il4_ip13_ra191.6882_dec49.8275_in7.npy



mask 1
tdat_il4_ip14_ra187.4889_dec46.9345_scl_in7.csv tmtx_il4_ip14_ra187.4889_dec46.9345_in7.npy



mask 1
tdat_il4_ip15_ra197.0965_dec39.5006_scl_in7.csv tmtx_il4_ip15_ra197.0965_dec39.5006_in7.npy



mask 1
tdat_il4_ip16_ra187.4889_dec46.9344_scl_in7.csv tmtx_il4_ip16_ra177.5102_dec52.0359_in7.npy



mask 0
tdat_il4_ip17_ra170.8056_dec43.5411_scl_in7.csv tmtx_il4_ip17_ra170.8056_dec43.5411_in7.npy



mask 1
tdat_il4_ip18_ra197.8840_dec38.4552_scl_in7.csv tmtx_il4_ip18_ra197.8840_dec38.4552_in7.npy



mask 1
tdat_il4_ip19_ra178.0183_dec60.5293_scl_in7.csv tmtx_il4_ip19_ra178.0183_dec60.5293_in7.npy



mask 0


In [4]:
a = np.array([[0, 0, 0.2],
              [0.9, 0, 0.4],
              [0.2, 0.5, 0.1]])
print(np.where(a < 0.3, 0, 1))

[[0 0 0]
 [1 0 1]
 [0 1 0]]
